export type ServerLogEventType =
  | 'OPERATION_RECEIVED'
  | 'BASE_VERSION_VALIDATED'
  | 'BASE_VERSION_MISMATCH'
  | 'OPERATION_APPLIED'
  | 'OPERATION_REJECTED'
  | 'DOCUMENT_VERSION_INCREMENTED'
  | 'CONFLICT_CREATED'
  | 'RESOLUTION_STARTED'
  | 'RESOLUTION_STEP'
  | 'RESOLUTION_COMPLETED'
  | 'STATE_PERSISTED'
  | 'SYNC_DISPATCHED';
